#!/bin/zsh

alias tpd="gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled false"
alias tpe="gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled true"
alias tpc="gsettings get org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled"

tt() {
  if $(tpc);
  then
    tpd; sleep 0.05; tpd; echo "Touchpad disabled";
  else
    tpe; echo "Touchpad enabled";
  fi
}

tt
